config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  
  resources :employees do
    collection { post :import }
  end
   root to: 'employees#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
        
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
            all.each do |employee|  
              csv << employee.attributes.values
            end
        end
    end
    def self.import(file)
        spreadsheet = open_spreadsheet(file)
        header = spreadsheet.row(1)
        (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        employee = find_by_id(row["id"]) || new
        employee.attributes = row.to_hash
        employee.save!
        end
    end

    def self.open_spreadsheet(file)
        case File.extname(file.original_filename)
        when ".csv" then Roo::CSV.new(file.path, packed: nil, file_warning: :ignore)
        when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
        when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
        else raise "Unknown file type: #{file.original_filename}"
        end
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  def index
    @employees = Employee.all
    respond_to do |format|
      format.html
      format.csv { send_data @employees.to_csv}
      format.xls { send_data @employees.to_csv(col_sep: "\s") }
    end
  end

  def import
    Employee.import(params[:file])
    redirect_to root_url, notice: "Product imported."
  end

  def show
    @employee = Employee.find(params[:id])
    #byebug
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    redirect_to @employee
  end

  def update
    @employee = Employee.find(params[:id])
    @employee.update(employee_params)
    redirect_to @employee
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to @employee
  end

  private 
  def employee_params
    params.require(:employee).permit(:name, :area, :city)  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<h1> Enter Data </h1>

<%= form_with(model: @employee, local: true) do |form| %>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
   
    <p>
      <%= form.label :area %><br>
      <%= form.text_area :area %>
    </p>

    <p>
      <%= form.label :city %><br>
      <%= form.text_area :city %>
    </p>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/employees/edit.html.erb
<%= render 'form' %>

app/views/employees/index.html.erb
<h1> Listing All Data </h1>

<%= link_to 'New Record', new_employee_path %>
<p>
  Download:
  <%= link_to "CSV", employees_path(format: "csv") %> |
  <%= link_to "Excel", employees_path(format: "xls") %>
</p>

<table>
    <tr>
        <th> Name </th>
        <th> Area </th>
        <th> City </th>
    </tr>

    <% @employees.each do |employee| %>
        <tr>
            <td><%= employee.name %></td>
            <td><%= employee.area %></td>
            <td><%= employee.city %></td>
            <td><%= link_to 'Show', employee_path(employee) %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
            <td><%= link_to 'Destroy', employee_path(employee), 
                            method: :"delete",
                            data: {confirm: "Are You Sure"} %> </td> 
        </tr>
        <% end %>
</table>

<h2>Import Employee data</h2>

<%= form_tag import_employees_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<p><%#= link_to "Printable Receipt (PDF)", meters_path(@meters, format: "pdf"), target: '_blank' %></p>

app/views/employees/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">City</Data></Cell>
      </Row>
    <% @employees.each do |employee| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= employee.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= employee.area %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= employee.city %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/employees/new.html.erb
<%= render 'form' %>

app/views/employees/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
 
<p>
  <strong>Area:</strong>
  <%= @employee.area %>
</p>
<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<%= link_to 'Back',employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>